app_uno/andromeda/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views #Importamos las vistas.


app_name = "andromeda" #Nombre de la aplicación

#Diseño de las urls a partir de las vistas creadas en views.py.
urlpatterns = [
	path('register/', views.registerPage, name="register"), #Creamos url personalizado para registrar cuentas.
	path('accounts/login/', views.loginPage, name="login"), #Creamos url personalizado para logear cuentas.
	path('logout/', views.logoutUser, name="logout"), #Creamos url personalizado para salir de una cuenta.

	path('', views.IndexView.as_view(), name="index"), #url personalizada para la vista del índice.
	#path('contact/', views.Contact.as_view(), name="contact"),
	path('review/', views.ReviewView.as_view(), name="reviews"), #url personalizada para la vista de las reseñas.
	path('review/<slug:slug>', views.ReviewDetailView.as_view(), name="review"), #url personalizada para la vista de reseñas detalladas.
	path('blog/', views.BlogView.as_view(), name="blogs"), #url personalizada para la vista de blogs.
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"), #url personalizada para la vista de los blogs detallados.
	path('upload-blog/', login_required(views.UploadBlog.as_view()), name = 'uploadblog'), #url personalizada para la vista de la sección para subir blogs, además requiere de un usuario logeado para acceder a la sección.
	path('upload-review/', login_required(views.UploadReview.as_view()), name = 'uploadreview'), #url personalizada para la vista de la sección para subir reseñas.
	]



app_uno/app_uno/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#Agrega los urls de la aplicación al proyecto.
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('andromeda.urls', namespace="andromeda")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_uno/andromeda/models.py
#Importamos librerías a utilizar en el avance del código.
from audioop import reverse
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

#Creación de objetos para la tabla de reseñas.
class Review(models.Model):

    class Meta:
        verbose_name_plural = 'Review Profiles' #Nombre plural para el campo en la sección de administración de Django.
        verbose_name = 'Review' #Nombre singular para el campo en la sección de administración de Django.
        ordering = ['-id'] #Ordenamos los datos de manera descendente.
    
    date = models.DateTimeField(blank=True, null=True) #Creamos la variable para guardar la fecha y asignamos su tipo de dato.
    author = models.CharField(max_length=200, blank=True, null=True) #Creamos la variable para guardar el autor y asignamos su tipo de dato.
    name = models.CharField(max_length=200, blank=True, null=True) #Creamos la variable para guardar el título y asignamos su tipo de dato.
    description = models.CharField(max_length=500, blank=True, null=True) #Creamos la variable para guardar la descripción y asignamos su tipo de dato.
    body = RichTextField(blank=True, null=True) #Creamos la variable para guardar el contenido y asignamos su tipo de dato.
    image = models.ImageField(blank=True, null=True, upload_to="review") #Creamos la variable para guardar la imagen y asignamos su tipo de dato.
    slug = models.SlugField(null=True, blank=True) 
    is_active = models.BooleanField(default=True) #Creamos variable para determinar si la reseña está activo.

    #Función que permite guardar los datos en un slug para hacerlos visibles cuando se entre a un URL referido.
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Review, self).save(*args, **kwargs)

    #Función para representar los objetos de clase como una cadena.
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/review/{self.slug}"

#Creación de objetos para la tabla de reseñas.
class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles' #Nombre plural para el campo en la sección de administración de Django.
        verbose_name = 'Blog' #Nombre singular para el campo en la sección de administración de Django.
        ordering = ["-id"] #Ordenamos los datos por fecha.

    #Creamos las variables y el tipo de dato que albergarán.
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True) #Creamos la variable para guardar el autor y asignamos su tipo de dato.
    name = models.CharField(max_length=200, blank=True, null=True) #Creamos la variable para guardar el título y asignamos su tipo de dato.
    description = models.CharField(max_length=500, blank=True, null=True) #Creamos la variable para guardar la descripción y asignamos su tipo de dato.
    body = RichTextField(blank=True, null=True) #Creamos la variable para guardar el contenido y asignamos su tipo de dato.
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog") #Creamos la variable para guardar la imagen y asignamos su tipo de dato.
    is_active = models.BooleanField(default=True) #Creamos variable para determinar si el blog está activo.

    #Función que permite guardar los datos en un slug para hacerlos visibles cuando se entre a un URL referido.
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    #Función para representar los objetos de clase como una cadena.
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"





app_uno/andromeda/forms.py
from django import forms #Importamos la librería de formularios Django.
from . models import Blog

from ckeditor.fields import RichTextFormField

#Librerías para crear el formaulario de cuentas de usuario
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
    
#Creamos la clase para albergar la información el formulario.
class UploadForm(forms.ModelForm):

	#Creamos el formulario para el nombre del autor, su campo, y el tipo de dato que llevan dentro.
	author = forms.CharField(max_length=100, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.

	#Creamos el formulario para el nombre del anime, su campo, y el tipo de dato que llevan dentro.
	name = forms.CharField(max_length=254, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.


	#Creamos el formulario para la descripción del anime, su campo, y el tipo de dato que llevan dentro.		
	description = forms.CharField(max_length=254, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.


	#Creamos el formulario para el blog/review del anime, su campo, y el tipo de dato que llevan dentro.
	body = forms.CharField(max_length=100000, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.

	image = forms.ImageField()

	#Nueva clase para identificar el destino de los datos.
	class Meta:
		model = Blog #Este formulario almacena los datos en el modelo Blog.
		fields = ('author', 'name', 'description', 'body', 'image') #Campos que se utilzarán del modelo.
	
#Creamos la clase para albergar la información el formulario.
class UploadReview(forms.ModelForm):

	#Creamos el formulario para el nombre del autor, su campo, y el tipo de dato que llevan dentro.
	author = forms.CharField(max_length=100, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.

	#Creamos el formulario para el nombre del anime, su campo, y el tipo de dato que llevan dentro.
	name = forms.CharField(max_length=254, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.


	#Creamos el formulario para la descripción del anime, su campo, y el tipo de dato que llevan dentro.		
	description = forms.CharField(max_length=254, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.


	#Creamos el formulario para el blog/review del anime, su campo, y el tipo de dato que llevan dentro.
	body = forms.CharField(max_length=100000, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.

	image = forms.ImageField() #Definimos la variable de imagen y el tipo de dato.

	#Nueva clase para identificar el destino de los datos.
	class Meta:
		model = Blog #Este formulario almacena los datos en el modelo Blog.
		fields = ('author', 'name', 'description', 'body', 'image') #Campos que se utilzarán del modelo.

class CreateUserForm(UserCreationForm): #Definimos el objeto para crear el formulario.
	class Meta:
		model = User #Asignamos el modelo, para guardar los datos(Modelo por defecto de Django).
		fields = ['username', 'email', 'password1', 'password2'] #Definimos los campos que llevará el formulario.

app_uno/andromeda/views.py
#Importamos librerías a utilizar en el desarrollo del código.
from multiprocessing import context
from django.shortcuts import render
from django.contrib import messages
from django.views import generic
#Importar los modelos que se utilizarán en algunas vistas.
from .models import (
		Review,
		Blog
	)

from . forms import UploadForm #Importar formulario para subir un blog.
from . forms import CreateUserForm #Importar formulario para crear usuario.

#imports para la creación de funciones login/logout/register
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect

def registerPage(request): #Definimos la función para registrar a los usuarios.
	if request.user.is_authenticated: #Si el usuario está logeado.
		return redirect('andromeda:index') #Lo envía al índice.
	else: #Instrucción else
		form = CreateUserForm() #De no estar logeado, se envía el formulario para registro al usuario.
		if request.method == 'POST': #Instrucción if para validar los datos.
			form = CreateUserForm(request.POST) #Se llama al formulario.
			if form.is_valid(): #Si el formulario es válido
				form.save() #Se guardan los datos
				user = form.cleaned_data.get('username') #Se obtiene el nombre del usuario.
				messages.success(request, 'Account was created for '+user) #Mensaje que indica al usuario, que su cuenta ha sido creada.

				return redirect('andromeda:login') #Se envía al usuario a la página del login.
		

		context = {'form':form} #Permite mostrar la información del formulario.
		return render(request, 'main/register.html', context) #Si el usuario no tiene cuenta, se le redirige a la página de registro.

def loginPage(request): #Definimos la función para permitir que el usuario se logee.
	if request.user.is_authenticated: #Ciclo if/else para validar el logeo del usuario. 
		return redirect('andromeda:index')#Si el usuario está logeado, le envía al índice del sitio web.
	else: #Si no está logeado, debe ingresar sus datos, para tener acceso.
		if request.method == 'POST':
			username = request.POST.get('username') #Campo para validar el usuario.
			password = request.POST.get('password') #Campo para validar la contraseña.

			user = authenticate(request, username=username, password=password) #Verifica si los datos son correctos.

			if user is not None: #Si los datos ingresados son válidos, le permite ingresar.
				login(request, user)
				return redirect('andromeda:index') #Al tener datos correctos, envía al usuario al índice.
			else:
				messages.info(request, 'Username or password is incorrect') #Si los datos son incorrectos, se le indica al usuario que tiene errores.

		context = {} #Muestra y toma el contenido del formulario.
		return render(request, 'main/login.html', context) #Una vez se validen los datos, envía al usuario al login.

def logoutUser(request): #Definimos la función para que el usuario salga de la página.
	logout(request)
	return redirect ('andromeda:login') #Cuando el usuario sale de su cuenta,lo envía a esta dirección.

#Se crea el constructor u objeto para la vista del índice.
class IndexView(generic.TemplateView):
	template_name = "main/index.html" #Agregamos el nombre del archivo HTML al que queremos hacer referencia en la vista.

	#Función para obtener los datos de los archivos que deseamos mostrar.
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		#Instanciamos los objetos que serán visibles en el ídnice.
		review = Review.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		
		#Se agregan las secciones visibles en el índice.
		context["review"] = review
		context["blogs"] = blogs
		return context

#Se crea el constructor u objeto para la vista de las reseñas..
class ReviewView(generic.ListView):
	model = Review #Tabla de donde se obtiene la información para la vista.
	template_name = "main/review.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.
	paginate_by = 10

	def get_queryset(self): #Se obtienen los registros guardados.
		return super().get_queryset().filter(is_active=True)

#Se crea el constructur u objeto para la vista de reseñas detalladas.
class ReviewDetailView(generic.DetailView):
	model = Review #Tabla de donde se obtiene la información para la vista.
	template_name = "main/review-detail.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.

#Se crea el constructur u objeto para los blogs.
class BlogView(generic.ListView):
	model = Blog #Tabla de donde se obtiene la información para la vista.
	template_name = "main/blog.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.
	paginate_by = 10
	
	def get_queryset(self): #Se obtienen los registros guardados.
		return super().get_queryset().filter(is_active=True)

#Se crea el constructur u objeto para ver lo sblogs detallados.
class BlogDetailView(generic.DetailView):
	model = Blog #Tabla de donde se obtiene la información para la vista.
	template_name = "main/blog-detail.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.

#Se crea el constructur u objeto para subir blogs.
class UploadBlog(generic.FormView):
	form_class = UploadForm #Tabla de donde se obtiene la información para la vista.
	template_name = "main/upload-blog.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.
	success_url = '/' #Colocamos el signo que se coloca al terminar la url.

	def form_valid(self, form): #Creamos la función para validar los datos.
		form.save() #Si el formulario está completo, se guardan los datos el el modelo correspondiente.
		return super().form_valid(form)

#Se crea el constructur u objeto para subir reseñas.
class UploadReview(generic.FormView):
	form_class = UploadForm #Tabla de donde se obtiene la información para la vista.
	template_name = "main/upload-review.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.
	success_url = '/' #Colocamos el signo que se coloca al terminar la url.

	def form_valid(self, form): #Creamos la función para validar los datos.
		form.save() #Si el formulario está completo, se guardan los datos el el modelo correspondiente.
		return super().form_valid(form)

app_uno/andromeda/templates/main/partials/footer.html
{% load static %}
<!--==================== INICIO DEL FOOTER  ====================-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://twitter.com/heyissac"> <!-- Link que redirige a mi twitter -->
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i> <!-- logo de twitter -->
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.facebook.com/profile.php?id=100068142570350&is_tour_dismissed=true"> <!-- Lingk de referencia a mi pagina de facebook -->
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i> <!--Logo de facebook-->
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/Heyissac"> <!--Link de referencia para el instagram-->
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i> <!--Logo de github-->
                            </span>
                        </a>
                    </li>
                </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy {% now 'Y' %}; Todos los derechos reservados. </div> <!--Copyright-->
            </div>
        </div>
    </div>
</footer>
<!--==================== FIN DEL FOOTER ====================-->

app_uno/andromeda/templates/main/partials/navigation.html
{% load static %}     
<!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'andromeda:index' %}">Shueisha</a> <!--Nombre de la página en la parte superir izquierda y su respectivo link de referencia-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0"> <!--Barra de navegación para las distintas ventanas-->
                    <!--Agregamos los items que agregaremos en la barra de navegación y referimos los distintos url para acceder a las distintas pestañas.-->
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'andromeda:index' %}">Inicio</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Blog</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'andromeda:blogs' %}">Blogs</a></li> 
                            <li><a class="dropdown-item" href="{% url 'andromeda:uploadblog' %}">Subir blog</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Review</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'andromeda:reviews' %}">Reseñas</a></li> 
                            <li><a class="dropdown-item" href="{% url 'andromeda:uploadreview' %}">Subir review</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        {% if request.user.is_authenticated %}
                        <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{user}}</a>
                        <ul class="dropdown-menu">
                            {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="dropdown-item" href="{% url 'andromeda:logout' %}">Log out</a></li>
                            {% else %}
                            <li class="nav-item"><a class="dropdown-item" href="{% url 'andromeda:login' %}">Log in</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'andromeda:register' %}">Registrar</a></li>
                        </ul>
                        {% else %}
                        <a class="nav-link dropdown-toggle px-lg-3 py-3 py-lg-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Cuenta</a>
                        <ul class="dropdown-menu">
                            {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="dropdown-item" href="{% url 'andromeda:logout' %}">Log out</a></li>
                            {% else %}
                            <li class="nav-item"><a class="dropdown-item" href="{% url 'andromeda:login' %}">Log in</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'andromeda:register' %}">Registrar</a></li>
                        </ul>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>