app_uno/andromeda/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views #Importamos las vistas.


app_name = "andromeda" #Nombre de la aplicación

#Diseño de las urls a partir de las vistas creadas en views.py.
urlpatterns = [
	path('register/', views.registerPage, name="register"), #Creamos url personalizado para registrar cuentas.
	path('accounts/login/', views.loginPage, name="login"), #Creamos url personalizado para logear cuentas.
	path('logout/', views.logoutUser, name="logout"), #Creamos url personalizado para salir de una cuenta.

	path('', views.IndexView.as_view(), name="index"), #url personalizada para la vista del índice.
	#path('contact/', views.Contact.as_view(), name="contact"),
	path('review/', views.ReviewView.as_view(), name="reviews"), #url personalizada para la vista de las reseñas.
	path('review/<slug:slug>', views.ReviewDetailView.as_view(), name="review"), #url personalizada para la vista de reseñas detalladas.
	path('blog/', views.BlogView.as_view(), name="blogs"), #url personalizada para la vista de blogs.
	path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blog"), #url personalizada para la vista de los blogs detallados.
	path('upload-blog/', login_required(views.UploadBlog.as_view()), name = 'uploadblog'), #url personalizada para la vista de la sección para subir blogs, además requiere de un usuario logeado para acceder a la sección.
	path('upload-review/', login_required(views.UploadReview.as_view()), name = 'uploadreview'), #url personalizada para la vista de la sección para subir reseñas.
	]



app_uno/app_uno/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#Agrega los urls de la aplicación al proyecto.
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('andromeda.urls', namespace="andromeda")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_uno/andromeda/models.py
#Importamos librerías a utilizar en el avance del código.
from audioop import reverse
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField

#Creación de objetos para la tabla de reseñas.
class Review(models.Model):

    class Meta:
        verbose_name_plural = 'Review Profiles' #Nombre plural para el campo en la sección de administración de Django.
        verbose_name = 'Review' #Nombre singular para el campo en la sección de administración de Django.
        ordering = ['-id'] #Ordenamos los datos de manera descendente.
    
    date = models.DateTimeField(blank=True, null=True) #Creamos la variable para guardar la fecha y asignamos su tipo de dato.
    author = models.CharField(max_length=200, blank=True, null=True) #Creamos la variable para guardar el autor y asignamos su tipo de dato.
    name = models.CharField(max_length=200, blank=True, null=True) #Creamos la variable para guardar el título y asignamos su tipo de dato.
    description = models.CharField(max_length=500, blank=True, null=True) #Creamos la variable para guardar la descripción y asignamos su tipo de dato.
    body = RichTextField(blank=True, null=True) #Creamos la variable para guardar el contenido y asignamos su tipo de dato.
    image = models.ImageField(blank=True, null=True, upload_to="review") #Creamos la variable para guardar la imagen y asignamos su tipo de dato.
    slug = models.SlugField(null=True, blank=True) 
    is_active = models.BooleanField(default=True) #Creamos variable para determinar si la reseña está activo.

    #Función que permite guardar los datos en un slug para hacerlos visibles cuando se entre a un URL referido.
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Review, self).save(*args, **kwargs)

    #Función para representar los objetos de clase como una cadena.
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/review/{self.slug}"

#Creación de objetos para la tabla de reseñas.
class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles' #Nombre plural para el campo en la sección de administración de Django.
        verbose_name = 'Blog' #Nombre singular para el campo en la sección de administración de Django.
        ordering = ["-id"] #Ordenamos los datos por fecha.

    #Creamos las variables y el tipo de dato que albergarán.
    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True) #Creamos la variable para guardar el autor y asignamos su tipo de dato.
    name = models.CharField(max_length=200, blank=True, null=True) #Creamos la variable para guardar el título y asignamos su tipo de dato.
    description = models.CharField(max_length=500, blank=True, null=True) #Creamos la variable para guardar la descripción y asignamos su tipo de dato.
    body = RichTextField(blank=True, null=True) #Creamos la variable para guardar el contenido y asignamos su tipo de dato.
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog") #Creamos la variable para guardar la imagen y asignamos su tipo de dato.
    is_active = models.BooleanField(default=True) #Creamos variable para determinar si el blog está activo.

    #Función que permite guardar los datos en un slug para hacerlos visibles cuando se entre a un URL referido.
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Blog, self).save(*args, **kwargs)

    #Función para representar los objetos de clase como una cadena.
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"





app_uno/andromeda/forms.py
from django import forms #Importamos la librería de formularios Django.
from . models import Blog

from ckeditor.fields import RichTextFormField

#Librerías para crear el formaulario de cuentas de usuario
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
    
#Creamos la clase para albergar la información el formulario.
class UploadForm(forms.ModelForm):

	#Creamos el formulario para el nombre del autor, su campo, y el tipo de dato que llevan dentro.
	author = forms.CharField(max_length=100, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.

	#Creamos el formulario para el nombre del anime, su campo, y el tipo de dato que llevan dentro.
	name = forms.CharField(max_length=254, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.


	#Creamos el formulario para la descripción del anime, su campo, y el tipo de dato que llevan dentro.		
	description = forms.CharField(max_length=254, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.


	#Creamos el formulario para el blog/review del anime, su campo, y el tipo de dato que llevan dentro.
	body = forms.CharField(max_length=100000, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.

	image = forms.ImageField()

	#Nueva clase para identificar el destino de los datos.
	class Meta:
		model = Blog #Este formulario almacena los datos en el modelo Blog.
		fields = ('author', 'name', 'description', 'body', 'image') #Campos que se utilzarán del modelo.
	
#Creamos la clase para albergar la información el formulario.
class UploadReview(forms.ModelForm):

	#Creamos el formulario para el nombre del autor, su campo, y el tipo de dato que llevan dentro.
	author = forms.CharField(max_length=100, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.

	#Creamos el formulario para el nombre del anime, su campo, y el tipo de dato que llevan dentro.
	name = forms.CharField(max_length=254, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.


	#Creamos el formulario para la descripción del anime, su campo, y el tipo de dato que llevan dentro.		
	description = forms.CharField(max_length=254, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.


	#Creamos el formulario para el blog/review del anime, su campo, y el tipo de dato que llevan dentro.
	body = forms.CharField(max_length=100000, required=True,) #Definimos cantidad máxima de caracteres y si el campo es obligatorio.

	image = forms.ImageField() #Definimos la variable de imagen y el tipo de dato.

	#Nueva clase para identificar el destino de los datos.
	class Meta:
		model = Blog #Este formulario almacena los datos en el modelo Blog.
		fields = ('author', 'name', 'description', 'body', 'image') #Campos que se utilzarán del modelo.

class CreateUserForm(UserCreationForm): #Definimos el objeto para crear el formulario.
	class Meta:
		model = User #Asignamos el modelo, para guardar los datos(Modelo por defecto de Django).
		fields = ['username', 'email', 'password1', 'password2'] #Definimos los campos que llevará el formulario.

app_uno/andromeda/views.py
#Importamos librerías a utilizar en el desarrollo del código.
from multiprocessing import context
from django.shortcuts import render
from django.contrib import messages
from django.views import generic
#Importar los modelos que se utilizarán en algunas vistas.
from .models import (
		Review,
		Blog
	)

from . forms import UploadForm #Importar formulario para subir un blog.
from . forms import CreateUserForm #Importar formulario para crear usuario.

#imports para la creación de funciones login/logout/register
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import redirect

def registerPage(request): #Definimos la función para registrar a los usuarios.
	if request.user.is_authenticated: #Si el usuario está logeado.
		return redirect('andromeda:index') #Lo envía al índice.
	else: #Instrucción else
		form = CreateUserForm() #De no estar logeado, se envía el formulario para registro al usuario.
		if request.method == 'POST': #Instrucción if para validar los datos.
			form = CreateUserForm(request.POST) #Se llama al formulario.
			if form.is_valid(): #Si el formulario es válido
				form.save() #Se guardan los datos
				user = form.cleaned_data.get('username') #Se obtiene el nombre del usuario.
				messages.success(request, 'Account was created for '+user) #Mensaje que indica al usuario, que su cuenta ha sido creada.

				return redirect('andromeda:login') #Se envía al usuario a la página del login.
		

		context = {'form':form} #Permite mostrar la información del formulario.
		return render(request, 'main/register.html', context) #Si el usuario no tiene cuenta, se le redirige a la página de registro.

def loginPage(request): #Definimos la función para permitir que el usuario se logee.
	if request.user.is_authenticated: #Ciclo if/else para validar el logeo del usuario. 
		return redirect('andromeda:index')#Si el usuario está logeado, le envía al índice del sitio web.
	else: #Si no está logeado, debe ingresar sus datos, para tener acceso.
		if request.method == 'POST':
			username = request.POST.get('username') #Campo para validar el usuario.
			password = request.POST.get('password') #Campo para validar la contraseña.

			user = authenticate(request, username=username, password=password) #Verifica si los datos son correctos.

			if user is not None: #Si los datos ingresados son válidos, le permite ingresar.
				login(request, user)
				return redirect('andromeda:index') #Al tener datos correctos, envía al usuario al índice.
			else:
				messages.info(request, 'Username or password is incorrect') #Si los datos son incorrectos, se le indica al usuario que tiene errores.

		context = {} #Muestra y toma el contenido del formulario.
		return render(request, 'main/login.html', context) #Una vez se validen los datos, envía al usuario al login.

def logoutUser(request): #Definimos la función para que el usuario salga de la página.
	logout(request)
	return redirect ('andromeda:login') #Cuando el usuario sale de su cuenta,lo envía a esta dirección.

#Se crea el constructor u objeto para la vista del índice.
class IndexView(generic.TemplateView):
	template_name = "main/index.html" #Agregamos el nombre del archivo HTML al que queremos hacer referencia en la vista.

	#Función para obtener los datos de los archivos que deseamos mostrar.
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		#Instanciamos los objetos que serán visibles en el ídnice.
		review = Review.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		
		#Se agregan las secciones visibles en el índice.
		context["review"] = review
		context["blogs"] = blogs
		return context

#Se crea el constructor u objeto para la vista de las reseñas..
class ReviewView(generic.ListView):
	model = Review #Tabla de donde se obtiene la información para la vista.
	template_name = "main/review.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.
	paginate_by = 10

	def get_queryset(self): #Se obtienen los registros guardados.
		return super().get_queryset().filter(is_active=True)

#Se crea el constructur u objeto para la vista de reseñas detalladas.
class ReviewDetailView(generic.DetailView):
	model = Review #Tabla de donde se obtiene la información para la vista.
	template_name = "main/review-detail.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.

#Se crea el constructur u objeto para los blogs.
class BlogView(generic.ListView):
	model = Blog #Tabla de donde se obtiene la información para la vista.
	template_name = "main/blog.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.
	paginate_by = 10
	
	def get_queryset(self): #Se obtienen los registros guardados.
		return super().get_queryset().filter(is_active=True)

#Se crea el constructur u objeto para ver lo sblogs detallados.
class BlogDetailView(generic.DetailView):
	model = Blog #Tabla de donde se obtiene la información para la vista.
	template_name = "main/blog-detail.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.

#Se crea el constructur u objeto para subir blogs.
class UploadBlog(generic.FormView):
	form_class = UploadForm #Tabla de donde se obtiene la información para la vista.
	template_name = "main/upload-blog.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.
	success_url = '/' #Colocamos el signo que se coloca al terminar la url.

	def form_valid(self, form): #Creamos la función para validar los datos.
		form.save() #Si el formulario está completo, se guardan los datos el el modelo correspondiente.
		return super().form_valid(form)

#Se crea el constructur u objeto para subir reseñas.
class UploadReview(generic.FormView):
	form_class = UploadForm #Tabla de donde se obtiene la información para la vista.
	template_name = "main/upload-review.html" #Plantilla HTML a donde iremos cuando ejecutemos esta vista.
	success_url = '/' #Colocamos el signo que se coloca al terminar la url.

	def form_valid(self, form): #Creamos la función para validar los datos.
		form.save() #Si el formulario está completo, se guardan los datos el el modelo correspondiente.
		return super().form_valid(form)

app_uno/andromeda/templates/main/blog.html
{% extends 'main/base.html' %} <!-- Hereda los atributos de la clase base-->
{% load static %} <!-- Carga la carpeta static -->

<!--=================================-->
{% block title %}{% endblock %}
<!-- ================================-->

<!--=================================-->
{% block extend_header %}{% endblock %}
<!--=================================-->

<!--=================================-->
{% block extend_footer %}{% endblock %}
<!--=================================-->
{% block content %}
<!DOCTYPE html>
<html lang="en">
<!-- Header de la página -->
<header class="masthead" style="background-image: url('/static/assets/img/ccc839332d89d6150db61b7e47da89f1.gif')"> <!-- referencia de imagen del header -->
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-x17">
        <div class="page-heading">
          <h1>Categoría: Blog</h1></br></br></br><!--Subtítulo del header -->
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Contenido principal de blog.html -->
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">Mira nuestros animés y mangas favoritos, entre otras opiniones</h1> <!--Pequeña descripción de la función de este apartado-->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <section class="page-section bg-light" id="portfolio2">
    <div class="container">
      <div class="row">
        {% for b in object_list %} <!--Ciclo for para buscar dentro de la bd -->
        <div class="col-lg-4 col-sm-6 mb-4">
          <!-- Aquí está el código para mostrar los blogs creados -->
          <div class="portfolio2-item">
            <a class="portfolio2-link" href="{% url 'andromeda:blog' slug=b.slug %}">
              <div class="portfolio2-hover">
                <!-- Clase para colocar la textura amarilla que aparece cuando se posiciona sobre un blog. -->
                <div class="portfolio2-hover-content"><i class="fas fa-plus fa-spin fa-3x"></i></div>
              </div>
              <img class="img-fluid2" src="{{b.image.url}}" alt="..." /> <!-- Muestra la imagen del blog -->
            </a>
            <div class="portfolio2-caption">
              <h4 class="portfolio2-caption-heading"><a href="{% url 'andromeda:blog' slug=b.slug %}">{{b.name}}</a> <!-- Título del blog, si se da clic permite ir al blog -->
              </h4>
              <div class="portfolio2-caption-subheading text-muted fst-italic">{{b.author}},
                {{b.timestamp.date}}</div> <!-- Nombre del autor y fecha de creación S-->
              <p>
                <a href="{% url 'andromeda:blog' slug=b.slug %}"></a> <!--Permite ir al blog -->
              </p>
            </div>
          </div>
        </div>
        {% endfor %} <!--Termina ciclo for -->
      </div>
  </section>

</html>
{%endblock%}

app_uno/andromeda/templates/main/index.html
{% extends 'main/base.html' %} <!-- Extiende del índice -->
{% load static %} <!-- Cargamos carpeta static -->

<!--=================================-->
{% block title %}{% endblock %}
<!-- ================================-->

<!--=================================-->
{% block extend_header %}{% endblock %} <!--Hereda los atributos del header-->
<!--=================================-->

<!--=================================-->
{% block extend_footer %}{% endblock %} <!--Hereda los atributos del footer-->
<!--=================================-->

<!--=================================== BODY ===================================-->
{% block content %}
<!DOCTYPE html>
<html lang="en">

<body>
    <!-- Header de la sección de índice -->
    <header class="masthead" style="background-image: url('static/assets/img/23-gif-ideas-in-2022-anime-wallpaper-live-kawaii-anime-anime-wallpaper.gif')"> <!-- En el header agregamos un gif -->
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Shueisha</h1> <!-- Título de la página en el header -->
                        <span class="subheading">Las mejores reseñas de los mejores mangas</span></br></br>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Contenido principal-->
    <!--Visualización de una sección de blogs en el índice-->
    <section class="page-section bg-light" id="portfolio">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase"><a href="{% url 'andromeda:blogs' %}">Blogs</a></h2> <!--Título de la sección de blogs, con acción y link de referencia para dirigirse la sección de blogs.-->
                <div class="post-preview">
                    <span class="post-meta text-center"> <!--Agregamos un estilo de texto y una especie de subtítulo contenido en la etiqueta span-->
                        ¿Te interesa? Sigue leyendo...
                    </span>
                </div>
            </div>
            <!-- Línea divisora de secciones -->
            <hr class="my-4" />

            <div class="row"> 
                {% for b in blogs|slice:":6" %} <!--Ciclo for para que muestre solo 6 blogs en el índice-->
                {% if b.is_active %}<!--Muestra solo los blogs que se encuentren activo en la sección de administración-->
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Aquí está el código para mostrar los blogs creados -->
                    <div class="portfolio-item">
                        <a class="portfolio-link" href="{% url 'andromeda:blog' slug=b.slug %}"> <!-- Mostrar los datos contenido en la sección de blogs ajustándos a los parámetros establecidos-->
                            <div class="portfolio-hover">
                                <!-- Clase para colocar la textura amarilla que aparece cuando se posiciona sobre un blog. -->
                                <div class="portfolio-hover-content"><i class="fas fa-plus fa-spin fa-3x"></i></div>
                            </div>
                            <img class="img-fluid2" src="{{b.image.url}}" alt="..." /> <!--Etiqueta de imagen que permite ver la imagen correspondiente al blog-->
                        </a>
                        <div class="portfolio-caption">
                            <h4 class="portfolio-caption-heading"><a
                                    href="{% url 'andromeda:blog' slug=b.slug %}">{{b.name}}</a></h4> <!-- Agregamos el nombre del blog -->
                            <div class="portfolio-caption-subheading text-muted fst-italic">{{b.author}},
                                {{b.timestamp.date}}</div> <!-- Agregamos el autor y la fecha de creación del blog -->
                            <p>
                                <a href="{% url 'andromeda:blog' slug=b.slug %}"></a> <!-- Línea para redirigir a la sección de blogs -->
                            </p>
                        </div>
                    </div>
                </div>
                {% endif %} <!--Se cierra ciclo if-->
                {% endfor %} <!--Se cierra ciclo for-->
            </div>
        </div>
    </section>

    <!-- Lúnea divisora -->
    <hr class="my-4" />

    <!-- Sección del índice para mostrar las reseñas -->
    <section>
        <div class="sectionSpace">
            <div class="container">
                <div class="col">
                    <h4 class="smText regular">Reseñas recientes</h4>
                </div>
                <div id="proof">
                    <div class="container-fluid p-0">
                        <div class="row g-0">
                            {% for p in review|slice:":3" %} <!-- Ciclo for para mostrar solo tres posiciones -->
                            {% if p.is_active %} <!-- Ciclo if para mostrar solo las reseñas que se encuentren activas -->
                            <div class="col-lg-4 col-sm-6">
                                <a class="proof-box" href="{% url 'andromeda:review' slug=p.slug %}"> <!--agregamos referencia para ir a la reseña cuando se haga clic sobre la imagen-->
                                    <img class="img-fluid" src="{{p.image.url}}" width="650" heigh="350" alt="..." /> <!--Muestra imagen correspondiente a la reseña -->
                                    <div class="proof-box-caption">
                                        <div class="project-category text-white-100">{{p.date}}, por: {{p.author}}</div> <!-- Muestra el autor y la fecha de creación de la reseña-->
                                        <div class="project-name text-white-100"
                                            href="{% url 'andromeda:review' slug=p.slug %}">{{p.name}}</div> <!-- Muestra el nombre de la reseña -->
                                    </div>
                                </a>
                            </div>
                            {% endif %} <!-- Cerramos ciclo if -->
                            {% endfor %} <!-- Cerramos ciclo for -->
                        </div>
        </div>
    </section>
</body>

</html>
{% endblock %}

app_uno/andromeda/templates/main/login.html
{% extends 'main/base.html' %} <!-- Extiende del índice -->
{% load static %} <!-- Cargamos carpeta static -->

<!--=================================-->
{% block title %}{% endblock %}
<!-- ================================-->

<!--=================================-->
{% block extend_header %}{% endblock %} <!--Hereda los atributos del header-->
<!--=================================-->

<!--=================================-->
{% block extend_footer %}{% endblock %} <!--Hereda los atributos del footer-->
<!--=================================-->
================================= -->
{% block content %}
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="login">
                                <div class="form">
                                  <h2>Bienvenido</h2>
                                  <input type="text" name="username" placeholder="Username">
                                  <input type="password" name="password" placeholder="Password">
                                  <input type="submit" value="Sign In" class="submit">
                                </div>
                                <div>
                                    <p class="mb-0">¿No tienes una cuenta? <a href="{% url 'andromeda:register' %}" class="text-white-50 fw-bold">Regístrate</a></br>
                                    </p>
                                  </div>
                              </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
</section>
{% endblock %}
<!-- ================================
End Content
================================= -->

app_uno/andromeda/templates/main/review-detail.html
{% extends 'main/base.html' %} <!-- hereda los atributos de la clase base -->
{% load static %} <!-- Carga la carpeta static -->

<!--=================================-->
{% block title %}{% endblock %}
<!-- ================================-->

<!--=================================-->
{% block extend_header %}{% endblock %} <!--Herda el header-->
<!--=================================-->

<!--=================================-->
{% block extend_footer %}{% endblock %} <!--Hereda el footer -->
<!--=================================-->
{% block content %} <!-- Contenido de la reseña -->
<!DOCTYPE html>
<html lang="en">
<!-- Page Header-->
<header class="masthead" style="background-image: url('{{object.image.url}}')"> <!--Imagen del background del header-->
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-xl7">
                <div class="page-heading">
                    <h1>{{object.name}}</h1> <!-- Muestra el nombre de la reseña -->
                    <span class="subheading">{{object.description}}</span> <!-- Muestra la descripción de la reseña -->
                </div>
            </div>
        </div>
    </div>
</header>

<body>

    <section>
        <div class="sectionSpaceSm">
            <div class="container">
                {{object.body|safe}} <!--Muestra el contneido de la reseña -->
            </div>
        </div>
    </section>
</body>

</html>
{% endblock %}

app_uno/andromeda/templates/main/review.html
{% extends 'main/base.html' %} <!-- Hereda los atributos del archivo base -->
{% load static %} <!-- Carga la carpeta static -->

<!--=================================-->
{% block title %}{% endblock %}
<!-- ================================-->

<!--=================================-->
{% block extend_header %}{% endblock %} <!-- Hereda el header -->
<!--=================================-->

<!--=================================-->
{% block extend_footer %}{% endblock %} <!-- Hereda el footer -->
<!--=================================-->
{% block content %} <!-- Mostrar bloque de contenido -->
<!DOCTYPE html>
<html lang="en">
<!-- Header de la página -->
<header class="masthead" style="background-image: url('/static/assets/img/a4206232b5b23615f764916e83efdbea.gif')"> <!-- Imagen del header -->
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-xl7">
        <div class="page-heading">
          <h1>Categoría: Reseñas</h1> <!-- Título agregado en el header -->
          <span class="subheading">Shueisha</span></br></br>
        </div>
      </div>
    </div>
  </div>
</header>
<!--CUERPO DE LA SECCIÓN DE RESEÑAS-->
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h3 class="animate-charcter"> Reseñas </h3>
      </div>
    </div>
  </div>
  <div id="proof2">
    <div class="container-fluid p-0">
        <div class="row g-0">
            {% for p in object_list %} <!-- Ciclo for para mostrar solo tres posiciones -->
            {% if p.is_active %} <!-- Ciclo if para mostrar solo las reseñas que se encuentren activas -->
            <div class="col-lg-4 col-sm-6">
                <a class="proof-box" href="{% url 'andromeda:review' slug=p.slug %}"> <!--agregamos referencia para ir a la reseña cuando se haga clic sobre la imagen-->
                    <img class="img-fluid" src="{{p.image.url}}" width="650" heigh="350" alt="..." /> <!--Muestra imagen correspondiente a la reseña -->
                    <div class="proof-box-caption">
                      <div class="project-name text-white-100"
                            href="{% url 'andromeda:review' slug=p.slug %}">{{p.name}}</div> <!-- Muestra el nombre de la reseña -->
                    </div>
                </a>
            </div>
            {% endif %} <!-- Cerramos ciclo if -->
            {% endfor %} <!-- Cerramos ciclo for -->
        </div>

</section>
</html>
{% endblock %}